/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 baloon.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Baloon = (props) => {
  const { nodes, materials } = useGLTF("/models/baloon.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Sphere.geometry}
        material={nodes.Sphere.material}
        position={[0, -0.248, 0]}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
        position={[0, -1.734, 0]}
        scale={0.071}
      />
      <meshStandardMaterial color="red" />
    </group>
  );
};

useGLTF.preload("/models/baloon.glb");

export default Baloon;
