"use client";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 baloon.glb 
*/

import React, { useRef } from "react";
import { Float, useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";

const Baloon = (props) => {
  const ref = useRef(null);

  const cubeClickHandler = () => {
    ref.current.applyImpulse({ x: 0, y: 10, z: 0 });
  };

  const { nodes, materials } = useGLTF("/models/baloon.glb");

  return (
    <Float speed={0.3} floatIntensity={0.1}>
      <RigidBody
        gravityScale={1.1}
        restitution={1}
        friction={0.01}
        ref={ref}
        // colliders="hull"
      >
        <group
          {...props}
          dispose={null}
          ref={ref}
          onPointerDown={cubeClickHandler}
        >
          <mesh
            geometry={nodes.Sphere.geometry}
            material={nodes.Sphere.material}
            position={[0, -0.248, 0]}
          >
            <meshStandardMaterial color={props.color} />
          </mesh>
          <mesh
            geometry={nodes.Cylinder.geometry}
            material={nodes.Cylinder.material}
            position={[0, -1.734, 0]}
            scale={0.071}
          >
            <meshStandardMaterial color={props.color} />
          </mesh>
        </group>
      </RigidBody>
    </Float>
  );
};

useGLTF.preload("/models/baloon.glb");

export default Baloon;
